### ISSUE TITLE
Inaccurate alignment of reads spanning short inversions

### ISSUE THREAD

**Issue by eldariont** [lh3/minimap2#112]
Hi,

I'm working with structural variation and compared NGM-LR (0.2.6) and minimap2 (2.8-r686) on a simulated dataset of mine. What I found is that minimap2 has problems with some inversions. Instead of mapping the read segment that stems from the inverted region to the other strand, it sometimes

**a) aligns the entire read with many mismatches** (NGM-LR and minimap2 alignments shown in the upper and lower track, respectively)
![ngmlr-minimap2_inv3](https://user-images.githubusercontent.com/6477692/36193712-3dcd8472-1167-11e8-84bd-434dd6ebcbab.png)

or **b) leaves the segment unmapped**. 
![ngmlr-minimap2_inv4](https://user-images.githubusercontent.com/6477692/36193714-3df024c8-1167-11e8-961b-484528f4453e.png)

I ran minimap2 with `minimap2 -ax map-pb -t 4 genome reads`. It seems as if inversions > 2kb are aligned alright but problems occur with shorter inversions. Any ideas on the reasons and/or ways to fix?

Cheers
David

**Comment by lh3** [comment]
(a) can be improved by reducing `-z`, though this comes at the cost of more fragmented alignment elsewhere. I am not sure about (b), though. Could you send me the few reads around the two inversions? I haven't carefully tune the parameters for small inversions. There should be some room for improvements. Thanks.

**Comment by eldariont** [comment]
Thanks for the quick reply! I will try out reducing the `-z`.

Here are the reads for the two examples:
[reads_inversion_a.fa.txt](https://github.com/lh3/minimap2/files/1724032/reads_inversion_a.fa.txt)
[reads_inversion_b.fa.txt](https://github.com/lh3/minimap2/files/1724033/reads_inversion_b.fa.txt)

I'm looking forward to what you find out.

**Comment by lh3** [comment]
The second case is due to a bug for reads mapped to the reverse strand. I will fix that. Stay tuned.

**Comment by lh3** [comment]
I have fixed the bug via c0e0d5d. If you run
```sh
minimap2 -axmap-pb -z200 ref.fa reads.fa
```
minimap2 should align the inversions. The next question is whether I should reduce `-z` to 200 by default. I will explore.

**Comment by eldariont** [comment]
Thanks for the quick fix!
I built the new version and tried aligning with `minimap2 -axmap-pb -z200 ref.fa reads.fa` but it produced at least one broken SAM record for my reads. This [problematic_read](https://github.com/lh3/minimap2/files/1727309/problematic_read.fa.txt) produces three separate [alignments](https://github.com/lh3/minimap2/files/1727310/problematic_read.sam.txt). The middle one only contains 9 (instead of 11) SAM fields with SEQ and QUAL missing which causes `samtools view` to fail on it.

Any ideas? I tried the same file with the r706 version and it produced (only) two proper alignment records for the read.

**Comment by lh3** [comment]
I am sorry for this. Please check out the master. Also, the master is effectively using `-z200` for inversions. You don't need to add `-z200`. If you want to find even smaller inversions, try
```sh
minimap2 -axmap-pb -z400,100 ref.fa reads.fa
```
The second threshold "100" is related to minimal inversion size. An excessively small value may slow down minimap2. I'd love to learn what the optimal threshold in your experiment. Thanks.

**Comment by eldariont** [comment]
The second parameter is super cool, thanks!
Unfortunately, I still have problems with, for instance, region b) from above. The read segments at the inversion all have mapping quality 0 and the one reversely mapped segment has a lot of mismatches:
![image](https://user-images.githubusercontent.com/6477692/36271262-68a273ac-127e-11e8-8e0e-951074e7b8d7.png)

I'm sorry to bother you again and hope that you can reproduce this with the `reads_inversion_b.fa` uploaded above. Cheers!

**Comment by lh3** [comment]
These excessive mismatches were caused by an old bug. I have now fixed this on the master branch. The latest code also assigns proper mapping quality to inversions.

Thanks a lot for these examples. Minimap2 inversion alignment actually never worked properly. Let me know if you see other issues. Sorry for the several round trips.

**Comment by eldariont** [comment]
Thanks a lot for all these quick fixes. The alignments around the inversions look much better now :)

I will continue exploring the alignments around my simulated SVs but think that we can close this issue for now if you don't mind.

**Comment by lh3** [comment]
FYI, I have just fixed a new bug related to the mapping quality of inversion alignment (#148).
